version: "3.7"

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=secret"
    volumes:
      - grafana-data:/var/lib/grafana/data

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/var/lib/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:6.8.1
    ports:
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/etc/logstash/logstash.conf
    command: logstash -f /etc/logstash/logstash.conf
    depends_on:
      - elasticsearch

volumes:
  grafana-data:
  prometheus-data:
  elasticsearch-data:
